# Demonstrating variables in python

name = "salman"

# print(name)

name = "python" 

# print(name)
age =20
hieght =1.8

# print(name)
# print(age)
# print(hieght)


PI = 3.142

# print(PI)

x = 10
y = 20

z =x + y

# print(z)

# define 2 variables a greeting and a name
greetin = "hello " 
name = "people"

inro = greetin + name

# print (inro)

# print( "The addition of  ",x," and ",y," will not be ",z,)

name = input("whats your name")
# print ("hello", name )

age = input('enter your age : ')
age = int(age)
print(type(age))
